#!/usr/bin/env bash


## Set GTK Themes, Icons, Cursor and Fonts

THEME='Catppuccin-Macchiato-Green'
ICONS='Desert-Dark-Icons'
FONT='Iosevka Nerd Font'
CURSOR='Posy_Cursor_Mono_Black'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
