## Import files (Colors, Fonts, Etc)
import:
  - ~/.config/hypr/alacritty/colors.yml
  - ~/.config/hypr/alacritty/fonts.yml

## Set environment variables
env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: '1.0'

## Terminal window settings
window:
  dimensions:
    columns: 82
    lines: 25

  padding:
    x: 12
    y: 12

  decorations: full
  startup_mode: Windowed
  dynamic_title: true

## scrolling
  history: 10000
  multiplier: 3

## Background opacity
  opacity: 0.8

  ## Default Shell
shell:
  program: /usr/bin/fish
 # args:
#    - --login
 

## Cursor
cursor:
  style:
    shape: Block
    blinking: On

  unfocused_hollow: false

## Live config reload
live_config_reload: true
